import axios from 'axios';
import { getPendingSales, removePendingSale } from './offlineStorage';
import toast from 'react-hot-toast';

export const syncOfflineSales = async () => {
  if (!navigator.onLine) return;

  const sales = await getPendingSales();
  if (sales.length === 0) return;

  const toastId = toast.loading(`Syncing ${sales.length} offline sales...`);

  let successCount = 0;
  let failCount = 0;

  for (const sale of sales) {
    try {
      // Remove the ID generated by IDB before sending to backend
      const { id, status, createdAt, ...payload } = sale;

      // Add flag to tell backend this is a sync
      await axios.post('/api/pos/sales', {
        ...payload,
        isOfflineSync: true
      });

      await removePendingSale(id);
      successCount++;
    } catch (error) {
      console.error('Failed to sync sale:', sale, error);
      failCount++;
    }
  }

  toast.dismiss(toastId);
  if (successCount > 0) toast.success(`Synced ${successCount} sales.`);
  if (failCount > 0) toast.error(`Failed to sync ${failCount} sales. Check console.`);
};
